"""empty message

Revision ID: 08f85e14c9ba
Revises: 313693f55214
Create Date: 2019-05-23 13:37:32.241974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f85e14c9ba'
down_revision = '313693f55214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config_filename', sa.String(length=127), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_instance', schema=None) as batch_op:
        batch_op.drop_column('config_filename')

    # ### end Alembic commands ###
