"""empty message

Revision ID: 313693f55214
Revises: 72e1c14aee5a
Create Date: 2019-05-08 15:05:19.265066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313693f55214'
down_revision = '72e1c14aee5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('build', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_build_instance_id_course_instance'), 'course_instance', ['instance_id'], ['key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('build', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_build_instance_id_course_instance'), type_='foreignkey')

    # ### end Alembic commands ###
