"""empty message

Revision ID: 4425d19cb30f
Revises: ef922816ddf5
Create Date: 2019-08-05 15:46:12.680079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4425d19cb30f'
down_revision = 'ef922816ddf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('build_log', schema=None) as batch_op:
        batch_op.drop_constraint('fk_build_log_number_build', type_='foreignkey')
        batch_op.drop_constraint('fk_build_log_instance_id_build', type_='foreignkey')

    with op.batch_alter_table('course_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin', sa.String(length=255), nullable=True))
        batch_op.drop_constraint('fk_course_instance_git_origin_git_repository', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_course_instance_origin_git_repository'), 'git_repository', ['origin'], ['origin'])
        batch_op.drop_column('git_origin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('git_origin', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_course_instance_origin_git_repository'), type_='foreignkey')
        batch_op.create_foreign_key('fk_course_instance_git_origin_git_repository', 'git_repository', ['git_origin'], ['origin'])
        batch_op.drop_column('origin')

    with op.batch_alter_table('build_log', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_build_log_instance_id_build', 'build', ['instance_id'], ['instance_id'])
        batch_op.create_foreign_key('fk_build_log_number_build', 'build', ['number'], ['number'])

    # ### end Alembic commands ###
