"""empty message

Revision ID: 52886b30696d
Revises: 08f85e14c9ba
Create Date: 2019-05-27 10:25:41.971022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52886b30696d'
down_revision = '08f85e14c9ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lft', sa.Integer(), nullable=False),
    sa.Column('rgt', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['group.id'], name=op.f('fk_group_parent_id_group'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group'))
    )
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.create_index('group_level_idx', ['level'], unique=False)
        batch_op.create_index('group_lft_idx', ['lft'], unique=False)
        batch_op.create_index('group_rgt_idx', ['rgt'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_name'), ['name'], unique=False)

    op.create_table('group_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('groups', 'courses', name='permtype'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_permission'))
    )
    op.create_table('gm_table',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('fk_gm_table_group_id_group')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_gm_table_user_id_user'))
    )
    op.create_table('gp_table',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('fk_gp_table_group_id_group')),
    sa.ForeignKeyConstraint(['permission_id'], ['group_permission.id'], name=op.f('fk_gp_table_permission_id_group_permission'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('roles')

    op.drop_table('gp_table')
    op.drop_table('gm_table')
    op.drop_table('group_permission')
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_name'))
        batch_op.drop_index('group_rgt_idx')
        batch_op.drop_index('group_lft_idx')
        batch_op.drop_index('group_level_idx')

    op.drop_table('group')
    # ### end Alembic commands ###
