"""empty message

Revision ID: 72e1c14aee5a
Revises: a19ed3038da3
Create Date: 2019-05-08 14:58:13.938506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e1c14aee5a'
down_revision = 'a19ed3038da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('build', schema=None) as batch_op:
        batch_op.drop_column('course_key')
        batch_op.drop_column('instance_key')

    with op.batch_alter_table('build_log', schema=None) as batch_op:
        batch_op.drop_column('course_key')
        batch_op.drop_column('instance_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('build_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instance_key', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('course_key', sa.VARCHAR(length=50), nullable=True))

    with op.batch_alter_table('build', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instance_key', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('course_key', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
