"""empty message

Revision ID: 986a184a823a
Revises: c1d2a8a8a601
Create Date: 2019-06-03 15:14:43.236770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986a184a823a'
down_revision = 'c1d2a8a8a601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gc_table',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('course_key', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_key'], ['course_repository.key'], name=op.f('fk_gc_table_course_key_course_repository')),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('fk_gc_table_group_id_group'))
    )
    with op.batch_alter_table('course_repository', schema=None) as batch_op:
        batch_op.drop_constraint('fk_course_repository_owner_id_group', type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_repository', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_course_repository_owner_id_group', 'group', ['owner_id'], ['id'])

    op.drop_table('gc_table')
    # ### end Alembic commands ###
