"""empty message

Revision ID: 99e29a6429f9
Revises: e9b47cc9d03a
Create Date: 2019-06-28 12:52:23.451438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e29a6429f9'
down_revision = 'e9b47cc9d03a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('git_repository',
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('private_key_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('origin', name=op.f('pk_git_repository'))
    )
    with op.batch_alter_table('course_instance', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_course_instance_git_origin_git_repository'), 'git_repository', ['git_origin'], ['origin'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_instance', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_course_instance_git_origin_git_repository'), type_='foreignkey')

    op.drop_table('git_repository')
    # ### end Alembic commands ###
