"""empty message

Revision ID: a19ed3038da3
Revises: c3d9177192a9
Create Date: 2019-05-08 14:39:01.674825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a19ed3038da3'
down_revision = 'c3d9177192a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('build', schema=None) as batch_op:
        batch_op.drop_constraint('fk_build_instance_id_course_instance', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('build', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_build_instance_id_course_instance', 'course_instance', ['instance_id'], ['id'])

    # ### end Alembic commands ###
