"""empty message

Revision ID: c1d2a8a8a601
Revises: 44b91eeb7977
Create Date: 2019-06-03 02:03:46.058998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d2a8a8a601'
down_revision = '44b91eeb7977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_repository', schema=None) as batch_op:
        batch_op.drop_constraint('fk_course_repository_owner_id_group', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_course_repository_owner_id_group'), 'group', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_repository', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_course_repository_owner_id_group'), type_='foreignkey')
        batch_op.create_foreign_key('fk_course_repository_owner_id_group', 'group', ['owner_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
