"""empty message

Revision ID: c3d9177192a9
Revises: 
Create Date: 2019-05-07 16:12:35.843984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d9177192a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_repository',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_course_repository')),
    sa.UniqueConstraint('key', name=op.f('uq_course_repository_key'))
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=True),
    sa.Column('sorting_name', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('id', name=op.f('uq_user_id'))
    )
    op.create_table('course_instance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('course_key', sa.String(length=50), nullable=False),
    sa.Column('git_origin', sa.String(length=255), nullable=True),
    sa.Column('secret_token', sa.String(length=127), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_key'], ['course_repository.key'], name=op.f('fk_course_instance_course_key_course_repository')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_instance'))
    )
    op.create_table('build',
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('course_key', sa.String(length=50), nullable=True),
    sa.Column('instance_key', sa.String(length=50), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Enum('PUBLISH', 'RUNNING', 'FINISHED', 'FAILED', name='states'), nullable=True),
    sa.Column('action', sa.Enum('CLONE', 'BUILD', name='action'), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['course_instance.id'], name=op.f('fk_build_instance_id_course_instance')),
    sa.PrimaryKeyConstraint('instance_id', 'number', name=op.f('pk_build'))
    )
    op.create_table('build_log',
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('course_key', sa.String(length=50), nullable=True),
    sa.Column('instance_key', sa.String(length=50), nullable=True),
    sa.Column('action', sa.Enum('CLONE', 'BUILD', name='action'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('log_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['build.instance_id'], name=op.f('fk_build_log_instance_id_build')),
    sa.ForeignKeyConstraint(['number'], ['build.number'], name=op.f('fk_build_log_number_build')),
    sa.PrimaryKeyConstraint('instance_id', 'number', 'action', name=op.f('pk_build_log'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('build_log')
    op.drop_table('build')
    op.drop_table('course_instance')
    op.drop_table('user')
    op.drop_table('course_repository')
    # ### end Alembic commands ###
