"""empty message

Revision ID: c98ae33da1e7
Revises: 99e29a6429f9
Create Date: 2019-07-05 11:54:02.085423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c98ae33da1e7'
down_revision = '99e29a6429f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jwt_token', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_instance', schema=None) as batch_op:
        batch_op.drop_column('jwt_token')

    # ### end Alembic commands ###
